---
###############################################################################
#
# absent.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# ENSURING SERVICE IS STOPPED
###############################################################################

- name: "Ensuring Postfix service is stopped"
  ansible.builtin.include_tasks: stopped.yml

###############################################################################
# ENSURING POSTFIX PACKAGE IS ABSENT
###############################################################################

- name: "Ensuring Postfix package is absent"
  ansible.builtin.include_tasks: package_absent.yml
  vars:
    iac_package: "{{ postfix_package }}"
