---
###############################################################################
#
# log_write.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# WRITING LOGS
###############################################################################

- name: "Writing task log through shared tasks"
  ansible.builtin.include_tasks: shared/log_write.yml
