---
###############################################################################
#
# present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# ENSURING POSTFIX PACKAGE IS PRESENT
###############################################################################

- name: "Ensuring Postfix package is installed"
  ansible.builtin.include_tasks: package_present.yml
  vars:
    iac_package: "{{ postfix_package }}"

- name: "Reloading systemd manager after Postfix package installation"
  ansible.builtin.systemd:
    daemon_reload: true

###############################################################################
# ENSURING POSTFIX CONFIGURATION IS PRESENT
###############################################################################

- name: "Ensuring Postfix configuration is present"
  ansible.builtin.include_tasks: configuration_present.yml
