---
###############################################################################
#
# restarted.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# ENSURING SYSTEMD SERVICE IS RESTARTED
###############################################################################

- name: "Ensuring Postfix service is restarted"
  ansible.builtin.systemd:
    name: "{{ postfix_service_name }}"
    state: "restarted"
    enabled: true

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Restarted service {{ postfix_service_name }}"
