---
###############################################################################
#
# started.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# ENSURING SYSTEMD SERVICE IS STARTED
###############################################################################

- name: "Ensuring Postfix service is started"
  ansible.builtin.systemd:
    name: "{{ postfix_service_name }}"
    state: "started"
    enabled: true

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Started service {{ postfix_service_name }}"
