---
###############################################################################
#
# stopped.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# ENSURING SYSTEMD SERVICE IS STOPPED
###############################################################################

- name: "Ensuring Postfix service is stopped"
  ansible.builtin.systemd:
    name: "{{ postfix_service_name }}"
    state: "stopped"
    enabled: false

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Stopped service {{ postfix_service_name }}"
