---
###############################################################################
#
# uninstall.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# ENSURING POSTFIX INSTALLATION AND CONFIGURATION IS ABSENT
###############################################################################

- name: "Ensuring Postfix installation is absent"
  ansible.builtin.include_tasks: absent.yml
